# User config
author: "Amy Hu"
tagline: "Portfolio Site"
description: "Hi, my name is Amy and Iâ€™m seeking opportunities in the intersection of art, engineering, and technology."
keywords: ""
email: "amyh1608@gmail.com"
instagram: "https://www.instagram.com/amy.makes/"
#twitter: ""
github: "https://github.com/amyh1608"


# Site config
url: "http://amy-hu.com"
#baseurl: "http://amy-hu.com"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed